/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import { Signer, utils, Contract, ContractFactory, Overrides } from "ethers";
import type { Provider, TransactionRequest } from "@ethersproject/providers";
import type { PromiseOrValue } from "../common";
import type { Random, RandomInterface } from "../Random";

const _abi = [
  {
    inputs: [],
    name: "Generate_Number",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    inputs: [],
    name: "rand_num",
    outputs: [
      {
        internalType: "uint8",
        name: "",
        type: "uint8",
      },
    ],
    stateMutability: "view",
    type: "function",
  },
];

const _bytecode =
  "0x608060405234801561001057600080fd5b50610345806100206000396000f3fe608060405234801561001057600080fd5b50600436106100365760003560e01c8063678892c01461003b5780639897c24014610059575b600080fd5b610043610077565b6040516100509190610124565b60405180910390f35b610061610088565b60405161006e9190610124565b60405180910390f35b60008054906101000a900460ff1681565b6000804340905060004282336040516020016100a69392919061020f565b6040516020818303038152906040528051906020012060001c905060016014826100d0919061027b565b6100da91906102db565b6000806101000a81548160ff021916908360ff16021790555060008054906101000a900460ff169250505090565b600060ff82169050919050565b61011e81610108565b82525050565b60006020820190506101396000830184610115565b92915050565b6000819050919050565b6000819050919050565b61016461015f8261013f565b610149565b82525050565b6000819050919050565b6000819050919050565b61018f61018a8261016a565b610174565b82525050565b600073ffffffffffffffffffffffffffffffffffffffff82169050919050565b60006101c082610195565b9050919050565b60008160601b9050919050565b60006101df826101c7565b9050919050565b60006101f1826101d4565b9050919050565b610209610204826101b5565b6101e6565b82525050565b600061021b8286610153565b60208201915061022b828561017e565b60208201915061023b82846101f8565b601482019150819050949350505050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601260045260246000fd5b60006102868261013f565b91506102918361013f565b9250826102a1576102a061024c565b5b828206905092915050565b7f4e487b7100000000000000000000000000000000000000000000000000000000600052601160045260246000fd5b60006102e68261013f565b91506102f18361013f565b9250828201905080821115610309576103086102ac565b5b9291505056fea26469706673582212208b1704a97a43bade9a58a562bd46ee1cebedf1e5c7cbd1e26242f6e804572c4d64736f6c63430008110033";

type RandomConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: RandomConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class Random__factory extends ContractFactory {
  constructor(...args: RandomConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override deploy(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): Promise<Random> {
    return super.deploy(overrides || {}) as Promise<Random>;
  }
  override getDeployTransaction(
    overrides?: Overrides & { from?: PromiseOrValue<string> }
  ): TransactionRequest {
    return super.getDeployTransaction(overrides || {});
  }
  override attach(address: string): Random {
    return super.attach(address) as Random;
  }
  override connect(signer: Signer): Random__factory {
    return super.connect(signer) as Random__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): RandomInterface {
    return new utils.Interface(_abi) as RandomInterface;
  }
  static connect(address: string, signerOrProvider: Signer | Provider): Random {
    return new Contract(address, _abi, signerOrProvider) as Random;
  }
}
